### ISSUE TITLE
Building apx on openSUSE Leap: creating completion fails with "panic: runtime error: slice bounds out of range [:2] with length 1"

### ISSUE THREAD

**Issue by johanneskastl** [Vanilla-OS/apx#424]
Dear maintainers,

I have an apx package for openSUSE, that builds (and works!) fine on Tumbleweed.

However on openSUSE Leap, the `go build` works, but creating the completions fails with the following error:

```
[   70s] + ./bin/apx completion bash
[   70s] panic: runtime error: slice bounds out of range [:2] with length 1
[   70s] 
[   70s] goroutine 1 [running]:
[   70s] github.com/vanilla-os/orchid.Locale(...)
[   70s]        /home/abuild/rpmbuild/BUILD/apx-2.4.4/vendor/github.com/vanilla-os/orchid/defaults.go:36
[   70s] github.com/vanilla-os/orchid/cmdr.getLocale({0xc000015a80?})
[   70s]        /home/abuild/rpmbuild/BUILD/apx-2.4.4/vendor/github.com/vanilla-os/orchid/cmdr/app.go:61 +0xdb
[   70s] github.com/vanilla-os/orchid/cmdr.NewApp({0x55d30159a1c8, 0x3}, {0x55d30159d885, 0xb}, {0x1?})
[   70s]        /home/abuild/rpmbuild/BUILD/apx-2.4.4/vendor/github.com/vanilla-os/orchid/cmdr/app.go:45 +0x147
[   70s] github.com/vanilla-os/apx/v2/cmd.New(...)
[   70s]        /home/abuild/rpmbuild/BUILD/apx-2.4.4/cmd/root.go:12
[   70s] main.main()
[   70s]        /home/abuild/rpmbuild/BUILD/apx-2.4.4/main.go:29 +0x4b
```

I tried building with go1.23, tried building static and with `CGO_ENABLED` set to 1 or 0. But to no avail.

Any idea what could cause this error?

Thanks in advance!

Kind Regards,
Johannes

**Comment by axtloss** [comment]
This seems to be caused by an issue in how we read the LANG envvar, could you show the contents of LANG in the build environment?

**Comment by johanneskastl** [comment]
Sure, it is set to `C.UTF-8` on both Leap and Tumbleweed.

**Comment by johanneskastl** [comment]
Setting `LANG=C.UTF-8` on Leap solves the errors when creating the completions.

I guess this is something that should be fixed, in case people run it on systems with `LANG` set to plain `C`?

**Comment by johanneskastl** [comment]
> I guess this is something that should be fixed, in case people run it on systems with `LANG` set to plain `C`?

Yup, running the binary from that package works with `LANG=de_DE.UTF-8`, but fails as soon as I set `LANG=C`,

**Comment by axtloss** [comment]
ok that's what I expected, it's an issue in our orchid library, I'll have to fix the locale detection
